### ISSUE TITLE
Installing and running needed some tweaks to work (on Linux)

### ISSUE THREAD

**Issue by anatexis** [gordonbrander/prompt_generator#2]
Hi,
I just read your "Generating your own Oblique Strategies" and was really intrigued by it!

Installing worked with:
```
git clone https://github.com/gordonbrander/prompt_generator.git
cd prompt_generator
pip3 install -r requirements.txt
```

Running worked with:

```
python3 ./runtracery.py ./grammars/prompt.json
```
Thank you for making this public!

**Comment by gordonbrander** [comment]
Thank you! It's just an afternoon hack, but I find these kinds of things very useful.

Landed a PR to fix README.
